# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8856683840cf7131b95d4ffd23443adec55b726d9b4864938f27586fcc725932b130091da0b43c85a33307c1318bb1d274dc90a7514302856c7b51e11416c9dd

test:
  secret_key_base: 36f05486e16ee385f5b5f92ee8d11cb1fe612a3d03c14864e28529bbf6164efa51dddf525abe0d5e317dbfadd2ff481d6fc31ac1b084ac9d716acc47f819c12e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
